### PR TITLE
Make configuration more flexible

### PR DESCRIPTION
**Pull request by ctessum**

### CODE REVIEW

**Comment by ctessum** [comment]
@dpaolella, I've modified the program to be able to use the https://github.com/spf13/viper configuration framework, and I've started adding in some of the configuration options from the configuration file. Would you be willing to add the rest when you get some time?

**Comment by ctessum** [comment]
The part that you would be adding to for the most part is in 202fa995c3990eb69bfe0a86bfab3ca704361fd8,  in the file cmd.go. The ```.md``` files are automatically generated by running ```go generate``` in the root directory.

**Comment by dpaolella** [comment]
Do we really want to add defaults for every configuration option? It seems unlikely that someone would want to run InMAP that way. I'm still trying to learn how viper works - is the ultimate goal here for there to be no config file, just a command line interface for setting up the config variables?

**Comment by ctessum** [comment]
I was thinking to have defaults for the things that have obvious defaults, like the variable grid thresholds. Otherwise, no default. The goals are allow users to have a general configuration file where they can override specific flags with command line arguments or environment variables, and to have the configuration documentation to be accessible from within the model in a way that can be used in a graphical user interface.

**Comment by dpaolella** [comment]
That makes sense.

**Comment by ctessum** [comment]
Thanks, David! When you get a chance, would you also be willing to add in the [rest of the configuration variables](https://github.com/spatialmodel/inmap/blob/master/inmaputil/config.go#L35) as well? It's not a super high priority.

**Pull request merged**
