### PR TITLE
draft, inmaputil: Modifying inmap.go to route certain outputs to Gobra

### PR DESCRIPTION
**Pull request by khoin**
Hi Chris,

This is the way I'd route messages from InMap to Gobra (web interface).

The browser isn't happy with it being bombarded with thousands of messages, so I couldn't add `CobraCommand.OutOrStdout()` to `mw` MultiWriter (in line 131 of inmaputil/inmap.go).

However, I routed some of the messages, and it was okay with that. 
Here's a screenshot showing the `percentage change since last convergence check` and the `adding grid cells...` but not the `iteration xxx walltime=[...]`.

Hope this makes sense. I figured you would know better about which messages you'd prefer to send to the browser as well, so this PR is merely a draft.

----
I am not exactly sure where to put the documentation for this because it's scattered everywhere, but here are different ways to print a message to the browser:
* Use `*cobra.Command` print methods when InMap is running with Gobra. E.g., Println, Printf, etc.
* Write to `*cobra.Command.OutOrStdout()` when InMap is running with Gobra ([this line](https://github.com/khoin/gobra/blob/master/gobra.go#L208) sets Cobra output to Gobra). E.g. `cmd.OutOrStdout().Write([]byte("Test"))`
* Write directly to `gobra.Server`. This struct implements `io.Writer` where `Write`ing to it will output on the browser. This struct gets pointed to by `OutOrStdout()` above when run with InMap/Cobra.

Let me know if anything is unclear.

image

### CODE REVIEW

**Comment by ctessum** [comment]
Thanks, Khoi. I think it's okay to send all of the log messages to the browser. It usually won't be a problem because under normal usage the model runs much more slowly than in the test cases, and if it continues to be a problem, we can just set it up to write log messages less often.

So I think what we can do is [this](https://github.com/spatialmodel/inmap/blob/master/inmaputil/inmap.go#L127) line, we can add `cmd.OutOrStdout` to the list of writers that are being logged to, and remove os.Stdout so that we're not logging the messages to the console twice.

Also, the the `eval` subdirectory is failing to compile, which I think you can fix by adding an empty `cmd` argument to the `Run()` functions in that directory.

**Comment by khoin** [comment]
Hi Chris,

I've routed the output directly to the Cobra.Command writer now. I've also fixed for the tests in eval/. The tests pass with Travis CI but fails on my laptop Windows computer for some reasons. I don't think I'll be able to track it down.

I thinks this should be good now. I'm not sure if this catches all outputs from the program, but I don't think I can track down all the output messages in time either.

**Comment by ctessum** [comment]
Thanks, Koi. This looks good. Just one thing: you need to run `dep ensure --update github.com/ctessum/gobra` and then commit the results to make sure the most recent version of gobra is getting used. If you don't have the correct versions of the dependencies installed (by using `dep ensure`) on your laptop that could also be what's causing the tests to fail for you.

**Comment by khoin** [comment]
updated gopkg.

**Comment by ctessum** [comment]
Thanks!

**Pull request merged**
